spring:
  datasource:
    url: ${spring.datasource.url}
    hikari:
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
      connection-timeout: ${spring.datasource.hikari.connection-timeout}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  application:
    name: companies-crud
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"


server:
  port: 8081
  servlet:
    context-path: /companies-crud

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE